# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Dockerfile for MCP Web Search Tool
FROM node:lts-alpine AS builder

WORKDIR /app

# Install dependencies without running prepare/build scripts
COPY package.json package-lock.json tsconfig.json ./
RUN npm install --ignore-scripts

# Copy source and build
COPY . .
RUN npm run build

# Production image
FROM node:lts-alpine
WORKDIR /app
ENV NODE_ENV=production

# Copy built artifacts and dependencies
COPY --from=builder /app/build ./build
COPY package.json package-lock.json ./
RUN npm install --omit=dev --ignore-scripts

# Run the MCP server via stdio
ENTRYPOINT ["node", "build/index.js"]
